POST http://localhost:5165/api/movies
Content-Type: application/json

{
  "Cim": "Eredet",
  "Evad": 0,
  "Hossz": 148,
  "Leiras": "Egy sci-fi akciófilm az álmok ellopásáról.",
  "PlakatKep": "",
  "Resz": 0,
  "Tipus": "Film"
}

### Új felhasználó létrehozása
POST http://localhost:5165/api/users
Content-Type: application/json

{
  "FelhNev": "MoziManias99",
  "Email": "teszt@email.com",
  "Jelszo": "TitkosJelszo123",
  "RegisztracioDatuma": "2026-06-02T00:00:00Z"
}

### Új értékelés beküldése
POST http://localhost:5165/api/ratings
Content-Type: application/json

{
  "FilmId": 1,
  "FelhasznaloId": 1,
  "Pontszam": 10,
  "SzovegesErtekeles": "Zseniális film, Christopher Nolan mesterműve!",
  "ErtekelisIdopontja": "2026-06-02T00:00:00Z"
}